PACKAGE LABA_5.TASK_3;
IMPORT JAVA.NIO.FILE.PATH;
IMPORT JAVA.NIO.FILE.PATHS;
IMPORT JAVA.NIO.FILE.STANDARDOPENOPTION;
IMPORT JAVA.io.FILE;
IMPORT JAVA.io.FILENOTFOUNDEXCEPTION;
IMPORT JAVA.io.IOEXCEPTION;
IMPORT JAVA.NIO.CHARSET.STANDARDCHARSETS;
IMPORT JAVA.NIO.FILE.FILES;
IMPORT JAVA.UTIL.SCANNER;
IMPORT JAVA.UTIL.COLLECTIONS;
IMPORT JAVA.UTIL.LOCALE;

PUBLIC CLASS FIRST_LAST_WORD_LETTER {
    PUBLIC STATIC VOID MAIN(STRING[] ARGS) {

        FILE FILE_1 = NEW FILE("C:\\USERS\\METEL\\IDEAPROJECTS\\MY_LAB_5\\SRC\\LABA_5\\TASK_3\\TEXT.TXT");
        PATH FILE_2_PATH = PATHs.GET("C:\\USERS\\METEL\\IDEAPROJECTS\\MY_LAB_5\\SRC\\LABA_5\\TASK_3\\FINISH_TEXT_2.TXT");
        FILE FILE_2 = NEW FILE("C:\\USERS\\METEL\\IDEAPROJECTS\\MY_LAB_5\\SRC\\LABA_5\\TASK_3\\FINISH_TEXT_2.TXT");

        if(FILE_2.DELETE()) {
            TRY {
                FILE_2.CREATENEWFILE();
            } CATCH (IOEXCEPTION e) {
                e.PRINTSTACKTRACE();
            }
        }

        SCANNER SCANNER = NULL;
        TRY {
            SCANNER = NEW SCANNER(FILE_1);
        } CATCH (FILENOTFOUNDEXCEPTION e) {
            e.PRINTSTACKTRACE();
        }

        WHILE(SCANNER.HASNEXTLINE()) {
            STRING FILE_LINE = SCANNER.NEXTLINE();
            FILE_LINE = FILE_LINE.REPLACEALL("\\PP", "");
            STRING[] WORDS = FILE_LINE.SPLIT(" ");
            STRING OUT = "";
            FOR (INT I=0; i < WORDS.LENGTH -1 ; ++I){
                STRING LAST_LETTER = WORDS[I].LENGTH() > 1 ? WORDS[I].SUBSTRING(WORDS[I].LENGTH()-1, WORDS[I].LENGTH()-0) : WORDS[I];
                STRING FIRST_LETTER = (WORDS[I + 1].LENGTH() > 1) ? WORDS[I + 1].SUBSTRING(0, 1) : WORDS[I + 1];
                if (LAST_LETTER.EQUALS(FIRST_LETTER)){
                    OUT = WORDS[I] + " " + WORDS[I+1];
                }
            }

            TRY {
                FILES.WRITE(FILE_2_PATH, COLLECTIONS.SINGLETON(OUT), STANDARDCHARSETS.UTF_8, STANDARDOPENOPTION.APPEND);
            } CATCH (IOEXCEPTION e) {
                e.PRINTSTACKTRACE();
            }
        }
    }
}
